language: objective-c
osx_image: xcode9.3
os: osx
sudo: false

cache:
  - bundler

before_install:
  - bundle install
  - bundle exec pod repo update

script:
  - bundle exec pod lib lint --allow-warnings
  - xcodebuild -workspace ConichiSDK.xcworkspace -scheme ConichiSDKStarterProject | xcpretty
  - bundle exec danger
