language: objective-c
osx_image: xcode8
sudo: false
cache:
- cocoapods

before_install:
    - export LANG=en_US.UTF-8
    - gem install bundler
    - bundle install --path=vendor/bundle --jobs=4 --retry=3 --without development

install:
    - bundle exec pod repo update

script:
    - bundle exec pod lib lint --allow-warnings
    - xcrun instruments -w '237D7619-4A4E-4624-8925-67A42A8A690A' || true
    - sleep 15
    - set -o pipefail && xcodebuild -workspace ConichiSDK.xcworkspace -scheme ConichiSDKStarterProject -destination 'platform=iOS Simulator,id=237D7619-4A4E-4624-8925-67A42A8A690A'
    - bundle exec danger --verbose
    - set -o pipefail && xcodebuild -project ConichiSDKStarterProject/ConichiSDKStarterProject.xcodeproj -scheme ConichiSDKStarterProject -destination 'platform=iOS Simulator,id=237D7619-4A4E-4624-8925-67A42A8A690A'
