rvm: 2.0.0
language: objective-c

cache:
- bundler
- cocoapods

before_install:
    - export LANG=en_US.UTF-8
    - bundle install --path=vendor/bundle --jobs=4 --retry=3 --without development

script:
    - bundle exec pod lib lint --allow-warnings
    - xcodebuild -workspace ConichiSDK.xcworkspace -scheme ConichiSDKStarterProject -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.1'
    - bundle exec danger --verbose
