require 'fileutils'

default_platform :ios

platform :ios do

  ############################## PRE ##############################

  before_all do
    skip_docs
    import_shared_fastfile
    load_environment_variables
  end

  ######################### PUBLIC LANES ##########################

  lane :release do |options|
    # ensure_branch
    #
    # pod_lib_lint(allow_warnings: true)

    release_version = options[:release_version]
    private_sdk_release = get_github_release(
      url: ENV['PRIVATE_CONICHI_IOS_SDK_GITHUB_REPO'],
      version: release_version,
      api_token: ENV['CONICHI_CI_GITHUB_TOKEN']
    )

    download_frameworks(release:private_sdk_release)

    update_changelog_from_release(release: private_sdk_release)

    upcoming_version = get_upcoming_version.clone
    put_upcoming_to_releases

    podspecs_version_bump(version: upcoming_version)

    remote = ENV['GITHUB_REMOTE']
    release_branch = ENV['GITHUB_RELEASE_BRANCH']

    git_add_or_update_tag(
      tag_name: upcoming_version,
      remote: remote,
      branch: release_branch
    )

    push_to_git_remote(
      remote: remote,
      local_branch: release_branch,
      remote_branch: release_branch
    )

    create_sample_project

    make_github_release(version: upcoming_version)

    podspecs_push
  end

  ######################### PRIVATE LANES ##########################

  desc "Push podspec files to remote"
  private_lane :podspecs_push do
    pod_push(path: ENV['CORE_KIT_PODSPEC'], allow_warnings: true)
    sh("bundle exec pod repo update")
    pod_push(path: ENV['PAYMENT_KIT_PODSPEC'], allow_warnings: true)
    sh("bundle exec pod repo update")
    pod_push(path: ENV['GEOFENCING_KIT_PODSPEC'], allow_warnings: true)
    pod_push(path: ENV['PMS_KIT_PODSPEC'], allow_warnings: true)
    pod_push(path: ENV['SUM_UP_KIT_PODSPEC'], allow_warnings: true)
    pod_push(path: ENV['PAYLEVEN_KIT_PODSPEC'], allow_warnings: true)
  end

  desc "Create or updaet github release with the given version"
  private_lane :make_github_release do |options|
    tag_name = options[:version]
    upcoming = get_releases[0]
    upcoming_notes = "* #{upcoming["notes"].join "\n* "} \n\n"
    set_or_update_github_release(
      release_name: tag_name,
      repository_name: ENV['GITHUB_REPOSITORY'],
      description: upcoming_notes,
      tag_name: tag_name,
      api_token: ENV['CONICHI_CI_GITHUB_TOKEN'],
      upload_assets: [ENV['FRAMEWROKS_FOLDER_ZIP_PATH'], ENV['CNISDK_SAMPLE_ZIP_PATH']]
    )
  end

  desc "Create the simple project"
  private_lane :create_sample_project do
    project_name = "SampleProject"
    path_dir = "../#{project_name}"
    FileUtils.mkdir(path_dir)
    FileUtils.cp_r("../Frameworks", path_dir)
    FileUtils.cp_r("../ConichiSDKStarterProject", path_dir)
    sh("zip -r ../#{project_name}.zip #{path_dir}")
    sh("rm -R #{path_dir}")
  end

  desc "Bump up podspec version number"
  private_lane :podspecs_version_bump do |options|
    version = options[:version]
    version_bump_podspec(path: ENV['CORE_KIT_PODSPEC'], version_number: version)
    version_bump_podspec(path: ENV['PAYMENT_KIT_PODSPEC'], version_number: version)
    version_bump_podspec(path: ENV['GEOFENCING_KIT_PODSPEC'], version_number: version)
    version_bump_podspec(path: ENV['PMS_KIT_PODSPEC'], version_number: version)
    version_bump_podspec(path: ENV['SUM_UP_KIT_PODSPEC'], version_number: version)
    version_bump_podspec(path: ENV['PAYLEVEN_KIT_PODSPEC'], version_number: version)

    git_commit_shell(message: "Bump podspecs to #{version}")
  end

  desc "Update changelog from private SDK changelog"
  private_lane :update_changelog_from_release do |options|
    require 'redcarpet'
    require 'redcarpet/render_strip'

    release = options[:release]
    release_version = release["tag_name"]

    markdown = Redcarpet::Markdown.new(Redcarpet::Render::StripDown)
    release_body_text = markdown.render(release["body"])
    release_changes = release_body_text.split("\n")

    changelog_data = get_changelog_data
    changelog_data["upcoming"]["version"] = release_version
    changelog_data["upcoming"]["notes"] = release_changes

    save_changelog_data(
      changelog_data: changelog_data
    )

    unless git_status_clean?
      git_commit_shell(
        message: "Update CHANGELOG with upcoming release information"
      )
    end
  end

  desc "Download private SDK frameworks"
  private_lane :download_frameworks do |options|
    release = options[:release]
    download_cnisdk_framework_zip_from_release(
      release: release,
      download_destination: ENV['CNISDK_FRAMEWORK_ZIP_PATH']
    )
    unzip(file: ENV['CNISDK_FRAMEWORK_ZIP_PATH'])
    copy_frameworks_from_cnisdk_framework_folder(
      cnisdk_framework_folder: "../Carthage/Build/iOS"
    )
  end

  desc "Ensure the branch is a release branch and no uncommitted changes"
  private_lane :ensure_branch do
    ensure_git_branch(branch: ENV['GITHUB_RELEASE_BRANCH'])
    ensure_git_status_clean
  end

  private_lane :import_shared_fastfile do
    import_from_git(
      url: "git@github.com:#{ENV['GITHUB_IOS_TEAM_REPOSITORY']}",
      branch: 'HEAD',
      path: 'fastlane/Fastfile'
    )
  end

  private_lane :load_environment_variables do
    sh("source ~/.bash_profile")
  end

  private_lane :copy_frameworks_from_cnisdk_framework_folder do |options|
    cnisdk_framework_folder = options[:cnisdk_framework_folder]
    frameworks_to_copy = ["CNISDKCoreKit.framework", "CNISDKGeoFencingKit.framework",
                          "CNISDKPaylevenKit.framework", "CNISDKPaymentKit.framework", "CNISDKPMSKit.framework",
                          "CNISDKSumUpKit.framework", "ios_global_dependencies.framework", "PaylevenFramework.framework"]
    frameworks_to_copy.each do |framework|
      FileUtils.cp_r("#{cnisdk_framework_folder}/#{framework}", "../Frameworks")
    end

    frameworks_folder_zip_name = ENV['FRAMEWROKS_FOLDER_ZIP_PATH']
    sh("zip -r ../#{frameworks_folder_zip_name} ../Frameworks")

    unless git_status_clean?
      cni_git_add(
        pathspec: "Frameworks/*"
      )
      git_commit_shell(
        message: "conichi frameworks have been updated;"
      )
    end
  end

  private_lane :download_cnisdk_framework_zip_from_release do |options|
    release = options[:release]
    assets = release["assets"]
    selected_assets = assets.select do |asset|
      asset["name"] == "CNISDK.framework.zip"
    end
    cnisdk_framework_zip_asset = selected_assets[0]
    url = cnisdk_framework_zip_asset["url"]
    download_destination = options[:download_destination]
    cni_download_github_release_asset(
      asset_url: url,
      destination_path: download_destination,
      api_token: ENV['CONICHI_CI_GITHUB_TOKEN']
    )
  end
end
