//
//  CNIError+API.h
//  conichiSDK
//
//  Created by Anton Domashnev on 1/11/16.
//  Copyright © 2016 conichi. All rights reserved.
//

#import "CNIError.h"

NS_ASSUME_NONNULL_BEGIN

/**
 * `CNIError+API` that contains all helper methods to create error for conichi SDK from conichi backend
 */
@interface CNIError (API)

/**
 *  Creates an NSError object with CNIErrorDomain. It can assign developerCode, developerMessage, underlyingError if exists
 *
 *  @param error              error generated by network framework
 *  @param responseStatusCode HTTP status code of the network response
 *  @param responseData       response data object
 *
 *  @return new error object
 */
+ (NSError *)errorWithResponseHTTPStatusCode:(NSInteger)responseStatusCode responseError:(nullable NSError *)error responseData:(nullable NSData *)responseData;

/**
 *  Creates an NSError object with CNIErrorDomain. It can assign developerCode, developerMessage, underlyingError if exists
 *
 *  @param error              error generated by network framework
 *  @param responseStatusCode HTTP status code of the network response
 *  @param responseObject     parsed response data
 *
 *  @return new error object
 */
+ (NSError *)errorWithResponseHTTPStatusCode:(NSInteger)responseStatusCode responseError:(nullable NSError *)error responseObject:(nullable id)responseObject;

@end

NS_ASSUME_NONNULL_END
