//
//  CNIError+ASSAAbloy.h
//  Conichi_Errors
//
//  Created by Mourad on 12/1/16.
//  Copyright © 2016 conichi. All rights reserved.
//

#import <Conichi_Errors/Conichi_Errors.h>

NS_ASSUME_NONNULL_BEGIN

/**
 * `CNIError+ASSAAbloy` that contains all helper methods to create error for conichi SDK from ASSA Abloy digital key provider
 */
@interface CNIError (ASSAAbloy)

/**
 *  Creates an NSError object with CNIErrorDomain. It can assign developerCode, developerMessage, underlyingError if exists
 *
 *  @param error generated by ASSA Abloy digital key provider
 *  @param message that will be added to the new returned error object. If it's nill, then there will be a custom message. 
 *
 *  @return new error object
 */
+ (NSError *)assaAbloyProviderErrorWithError:(nullable NSError *)error message:(nullable NSString *)message;
@end

NS_ASSUME_NONNULL_END
