//
//  CNIError+Payment.h
//  ios-utilities example
//
//  Created by Anton Domashnev on 01/07/16.
//  Copyright © 2016 conichi. All rights reserved.
//

#import "CNIError.h"


NS_ASSUME_NONNULL_BEGIN

/**
 * `CNIError+Payment` that contains all helper methods to create error for conichi SDK from payment provider cloud
 */
@interface CNIError (Payment)

/**
 *  Creates an NSError object with CNIErrorDomain. It can assign developerCode, developerMessage, underlyingError if exists
 *
 *  @param error generated by payment provider
 *
 *  @return new error object
 */
+ (NSError *)paymentProviderErrorWithError:(nullable NSError *)error;

@end

NS_ASSUME_NONNULL_END
